### ISSUE TITLE
Update FAQ for wget error

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-user-support#2]
## Error: “HTTP request to OpenID Relying Party service failed”

If the datanode uses a CA that isn't trusted by the client, this error is also returned.

-i will solve this.

**Comment by sashakames** [comment]
In this case -H was tried first, but -H -i solved the problem

**Comment by xffzcj** [comment]
I used the command bash-H-i on the Linux server but still displayed ERROR: HTTP request to OpenID Relying Party service failed.
Download failed
Done
